language: node_js
node_js:
  - "8"
? cache
directories:
  - node_modules
branchs:
  only:
    - master
sudo: true
notifications:
  email: false
script: true
deploy:
  provider: script
  script: bash ./deploy.sh
addons:
  ssh_known_hosts: 107.182.188.188:12306
before_install:
  - openssl aes-256-cbc -K $encrypted_8257990658f4_key -iv $encrypted_8257990658f4_iv
    -in id_rsa.enc -out id_rsa -d
