language: node_js
node_js:
- '8'
cache: 
directories:
- node_modules
branchs:
  only:
  - master
script: true
before_install:
- openssl aes-256-cbc -K $encrypted_8963483cfd80_key -iv $encrypted_8963483cfd80_iv
  -in id_rsa.enc -out /.ssh/id_rsa -d
