language: node_js
node_js:
  - "8"
? cache
directories:
  - node_modules
branchs:
  only:
    - master
addons:
  ssh_known_hosts:
    - 107.182.188.188 
script: true
before_install:
  - openssl aes-256-cbc -K $encrypted_8257990658f4_key -iv $encrypted_8257990658f4_iv
    -in id_rsa.enc -out ./id_rsa -d
after_success:
# - chmod 600 ~/.ssh/id_rsa
- ssh test@107.182.188.188 -p 12306 -o StrictHostKeyChecking=no 'mkdir /usr/src/fdsfe'   #使用ssh连接服务器
