language: node_js
node_js:
- '8'
cache: 
directories:
- node_modules
branchs:
  only:
  - master
sudo: true
notifications:
  email: false
script: true
# deploy:
#   provider: script
#   script: 
#     - ssh root@107.182.188.188 -p 12306 -o -v StrictHostKeyChecking=no
#     - bash deploy.sh
addons:
  ssh_known_hosts: 107.182.188.188:12306
before_install:
- openssl aes-256-cbc -K $encrypted_882236df0a8b_key -iv $encrypted_882236df0a8b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@107.182.188.188 -p 12306 -o StrictHostKeyChecking=no
- chmod +x deploy.sh