language: node_js
node_js:
  - "8"
? cache
directories:
  - node_modules
branchs:
  only:
    - master
script: true
before_install:
  - openssl aes-256-cbc -K $encrypted_8257990658f4_key -iv $encrypted_8257990658f4_iv
    -in id_rsa.enc -out ./id_rsa -d
